apiVersion: v1
kind: ConfigMap
metadata:
  name: amjira
  labels:
    codefresh.io/entity: integration-config
    codefresh.io/integration-type: issue.jira
data:
  host_url: 'https://ammar-ahmed-butt.atlassian.net'
  email: ammar.butt@atlassiancommunity.com
