kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: dockercode
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: dockercode
    codefresh.io/integration-type: registry.dockerhub
spec:
  template:
    metadata:
      name: dockercode
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
  encryptedData:
    password: >-
      AgByXdTmeabzYmaeMts2sFH/UQLog2RZGfikb+ClI/BVechN+KwKVFZ4bOl9Q1iKL5KIx5xdu5M3qu5jN20KsJFikt9C5rwSHSaZscaypwtCn8mlO0pxc8jVgOejZGWOUh4xYkihwKSMAhoQmSgpDTjXX7shPgdCKCURkomGCE221bS0OYXt9cj/NKK0rXsUlku8lpN5X0tg8t7unqaU9/3gPxWzNtCMB5AwmSz7tddRzvhKEzAeGJUZAR7j2zeRVbCigZ/4kXaA21aFkKYcVuR6ajqj5jKi8W6eADtY24i5Sbl5wI4AhDepyb8sMNezgSrIbsTHWzyMrlgBcS2+AC770k98MHWolM/WgRZa6sr29mMQx4cjopXUfTYN6i1D4CKyLpkK/t25/p9Fy2PGFmMDtmVkPMTzfmPhlxcPWu53HsJNrO6C72YPrD07i3VmE/k2/V4jBEbbeOH7iJiHL3j8uB+h+KF+g3eYE9ljf4vzzb36qTDgcXT3xIgiYoe4CbeMIps0vpX6+JYkOABi0LikzHJ2Pti/aNoKPiDWo3LswvZs093/IrmzNjodAkbHED9WvPPXlbwlQ/I9Smsp3BhvuomW8b0RSZHGsT72aBmRUnit0gyajiwYfZ0YwTNcrHopCTWQlT/pWS0dCkwoHJ+ETDzOzVW+0/by7N3TdUl+giK5OTcPUuplLYNcmpKbSudCgm4wSEh1Jfy49BCx
